//! @file
#ifndef QUERY_8_H
#define QUERY_8_H

#include <datatypes/datatypes.h>

/**
 * @brief Execute query 8 to get hotel total revenue
 *
 * Executes query 8 to calculate and write the total revenue generated by a hotel within a specified date range
 * into the output file.
 *
 * @param CATALOGS Catalogs created by the `catalogs_creator()` function
 * @param command_number The number associated with the command
 * @param format_flag Flag indicating the output format
 * @param name Name or ID of the hotel for revenue calculation
 * @param begin_date Start date of the revenue calculation period
 * @param end_date End date of the revenue calculation period
 * @return int Returns 0 upon successfully executing query 8
 */
int query_8(Catalogs CATALOGS, int command_number, bool format_flag, char* name, char* begin_date, char* end_date);

#endif