name: Check memory leaks [valgrind]
on: [pull_request]

jobs:
  build:
    name: Memory leaks Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Valgrind
      run: |
        sudo apt update
        sudo apt install -y valgrind
    
    - name: Download dataset from GitHub Assets
      working-directory: ./trabalho-pratico
      run: |
          curl -L \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --output "dataset.zip" \
            https://api.github.com/repos/Darguima/Trivial-Booking/releases/assets/140935140

          unzip dataset.zip

    - name: Build project
      working-directory: ./trabalho-pratico
      run: DEBUG=1 make

    - name: Run Valgrind
      working-directory: ./trabalho-pratico
      run: |
        make check-memory 2>&1 | tee valgrind_output.txt
        set -e
        if grep -q "ERROR SUMMARY: 0 errors" valgrind_output.txt; then
          echo "No memory leaks detected."
        else
          echo "Memory leaks detected!"
          exit 1
        fi

