name: Check queries [md5sum]
on: [pull_request]

jobs:
  build:
    name: Check queries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download dataset from GitHub Assets
      run: |
        wget https://github.com/Darguima/Trivial-Booking/releases/download/phase_1/dataset.zip
        unzip dataset.zip

    - name: Build with make
      working-directory: ./trabalho-pratico
      run: make test
