name: Check memory leaks [valgrind]
on: [pull_request]

jobs:
  build:
    name: Memory leaks Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Valgrind
      run: sudo apt install -y valgrind

    - name: Build project
      working-directory: ./trabalho-pratico
      run: DEBUG=1 make

    - name: Run Valgrind
      working-directory: ./trabalho-pratico
      run: |
        valgrind --leak-check=full ./programa-principal dataset/data dataset/inputs/input.txt 2>&1 | tee valgrind_output.txt
        set -e
        if grep -q "ERROR SUMMARY: 0 errors" valgrind_output.txt; then
          echo "No memory leaks detected."
        else
          echo "Memory leaks detected!"
          exit 1
        fi

