name: Check queries [md5sum]
on: [pull_request]

jobs:
  build:
    name: Check queries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download dataset from GitHub Assets
      working-directory: ./trabalho-pratico
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/releases

          unzip dataset.zip

    - name: Run tests
      working-directory: ./trabalho-pratico
      run: make test
